//
//  BasisZipAndUnzip+Other_userinfo.h
//  TestZip
//
//  Created by ran on 12-8-21.
//  Copyright (c) 2012年 ran. All rights reserved.
//

#import "BasisZipAndUnzip+gameInterface.h"

@interface BasisZipAndUnzip (Other_userinfo)



-(DZPK_SERVER_REQ_RECV_NEW_MSG * )PullREQ_RECV_NEW_MSG;
-(DZPK_SERVER_REQ_RECV_GET_MSG * )PullREQ_RECV_GET_MSGG;
-(DZPK_SERVER_REQ_GAME_RANKING * )PullREQ_GAME_RANKINGG;
-(void)PushREQ_GAME_RANKINGData:(DZPK_CLIENT_REQ_GAME_RANKING*)arr;
-(DZPK_SERVER_REQ_RECOMMENDATION * )PullREQ_RECOMMENDATIONG;
-(void)PushREQ_FEEDBACKData:(DZPK_CLIENT_REQ_FEEDBACK *)arr;
-(DZPK_SERVER_REQ_FEEDBACK *)PullREQ_FEEDBACKS;
-(DZPK_SERVER_REQ_SHARE_CONTENT*)PullREQ_SHARE_CONTENT;
-(void)PushREQ_CONVERTData:(DZPK_CLIENT_REQ_CONVERT *)arr;
-(DZPK_SERVER_REQ_CONVERT *)PullREQ_CONVERTS;
-(DZPK_SERVER_REQ_PERSON_DATA_HEAD_NAME *)PullREQ_PERSON_DATA_HEAD_NAME;
-(void)PushREQ_PERSON_DATA_ALTERData:(DZPK_CLIENT_REQ_PERSON_DATA_ALTER *)arr;
-(DZPK_SERVER_REQ_PERSON_DATA_ALTER *)PullREQ_PERSON_DATA_ALTER;
-(DZPK_SERVER_REQ_PERSON_DATA *)PullREQ_PERSON_DATA;

-(DZPK_SERVER_REQ_GET_CHIPS*)PullREQ_GET_CHIPS;
-(DZPK_SERVER_REQ_SYNC_SIGNAL_RESOURCE*)PullREQ_SYNC_SIGNAL_RESOURCE;
-(DZPK_SERVER_REQ_OFFLINE *)PullREQ_OFFLINE;
-(DZPK_SERVER_REQ_GET_TASK *)PullREQ_GET_TASK;
-(void)PushREQ_GET_BONUDSData:(DZPK_CLIENT_REQ_GET_BONUDS*)arr;
-(DZPK_SERVER_REQ_GET_BONUDS *)PullREQ_GET_BONUDS;
-(void)PushREQ_SHARE_CONTENTData:(DZPK_CLIENT_REQ_SHARE_CONTENT *)arr;
-(DZPK_SERVER_REQ_GET_ACTIVITY*)PullREQ_GET_ACTIVITY;
-(DZPK_SERVER_REQ_REALTIME_INFOR*)PullREQ_REALTIME_INFOR;
-(DZPK_SERVER_REQ_GET_ACTIVITY_HONUS*)PullREQ_GET_ACTIVITY_HOUNS;
-(void)PushREQ_SHARE_BOUNDData:(DZPK_CLIENT_REQ_SHARE_BONUS*)arr;
-(DZPK_SERVER_REQ_SHARE_BONUS*)PullREQ_SHARE_BOUND;

@end
