//
//  BasisZipAndUnzip+gameInterface.h
//  TestZip
//
//  Created by ran on 12-8-20.
//  Copyright (c) 2012年 ran. All rights reserved.
//

#import "BasisZipAndUnzip+loginAndcharge.h"

@interface BasisZipAndUnzip (gameInterface)

-(void)PushREQ_GAME_QUICKRData:(DZPK_CLIENT_REQ_GAME_QUICK *)arr;
-(DZPK_SERVER_REQ_GAME_QUICK_SERVER *)PullREQ_GAME_QUICK_SERVER;
-(DZPK_SERVER_REQ_GAME_QUICK *)PullREQ_GAME_QUICK;
-(DZPK_SERVER_REQ_GAME_ROOM_LIST_MATCH *)PullREQ_GAME_ROOM_LIST_MATCH;
-(void)PushREQ_GAME_ROOM_LIST_NORMALData:(DZPK_CLIENT_REQ_GAME_ROOM_LIST_NORMAL *)arr;
-(DZPK_SERVER_REQ_GAME_ROOM_LIST_NORMAL *)PullREQ_GAME_ROOM_LIST_NORMAL;
-(void)PushREQ_GAME_ENTER_ROOMData:(DZPK_CLIENT_REQ_GAME_ENTER_ROOM *)arr;
-(DZPK_SERVER_REQ_GAME_ENTER_ROOM *)PullREQ_GAME_ENTER_ROOM;
-(void)PushREQ_GAME_SEND_SEAT_ACTIONData:(DZPK_CLIENT_REQ_GAME_SEND_SEAT_ACTION *)arr;
-(DZPK_SERVER_REQ_GAME_SEND_SEAT_ACTION *)PullREQ_GAME_SEND_SEAT_ACTION;
-(void)PushREQ_GAME_SEND_MSGData:(DZPK_CLIENT_REQ_GAME_SEND_MSG *)arr;
-(DZPK_SERVER_REQ_GAME_SEND_MSG *)PullREQ_GAME_SEND_MSG;
-(void)PushREQ_GAME_SEND_ACTIONData:(DZPK_CLIENT_REQ_GAME_SEND_ACTION *)arr;
-(DZPK_SERVER_REQ_GAME_SEND_ACTION *)PullREQ_GAME_SEND_ACTION;
-(DZPK_SERVER_REQ_GAME_RECV_ACTION *)PullREQ_GAME_RECV_ACTION;
-(DZPK_SERVER_REQ_GAME_RECV_LEAVE *)PullREQ_GAME_RECV_LEAVE;
-(DZPK_SERVER_REQ_GAME_RECV_SEAT_DOWN *)PullREQ_GAME_RECV_SEAT_DOWN;
-(DZPK_SERVER_REQ_GAME_RECV_CARDS *)PullREQ_GAME_RECV_CARDS;
-(DZPK_SERVER_REQ_GAME_RECV_WINNER *)PullREQ_GAME_RECV_WINNERS;
-(void)PushREQ_GAME_TIMEOUT_BACKData:(DZPK_CLIENT_REQ_GAME_TIMEOUT_BACK *)arr;
-(DZPK_SERVER_REQ_GAME_TIMEOUT_BACK *)PullREQ_GAME_TIMEOUT_BACKS;
-(DZPK_SERVER_REQ_GAME_RECV_READYTIME *)PullREQ_GAME_RECV_READYTIME;
-(DZPK_SERVER_REQ_GAME_RECV_START_INFOR *)PullREQ_GAME_RECV_START_INFORE;
-(void)PushREQ_GAME_ADD_CHIPSData:(DZPK_CLIENT_REQ_GAME_ADD_CHIPS *)arr;
-(DZPK_SERVER_REQ_GAME_ADD_CHIPS *)PullREQ_GAME_ADD_CHIPSE;
-(DZPK_SERVER_REQ_GAME_RECV_MSG *)PullREQ_GAME_RECV_MSG;
-(DZPK_SERVER_REQ_GAME_CONNECT_AGAIN *)PullREQ_GAME_CONNECT_AGAIN;
-(void)PushREQ_GAME_SEARCH_ROOMData:(DZPK_CLIENT_REQ_GAME_SEARCH_ROOM *)arr;
-(DZPK_SERVER_REQ_GAME_SEARCH_ROOM *)PullREQ_GAME_SEARCH_ROOM;
-(DZPK_SERVER_REQ_GAME_RECV_OUT *)PullREQ_GAME_RECV_OUT;
-(void)PushREQ_GAME_PLAYER_DATAData:(DZPK_CLIENT_REQ_GAME_PLAYER_DATA *)arr;
-(DZPK_SERVER_REQ_GAME_PLAYER_DATA *)PullREQ_GAME_PLAYER_DATA;

-(DZPK_SERVER_REQ_GAME_USE_GIFT *)PullREQ_GAME_USE_GIFT;
-(void)PushREQ_GAME_USE_GIFTData:(DZPK_CLIENT_REQ_GAME_USE_GIFT *)arr;
-(DZPK_SERVER_REQ_GET_COUNTDOWN_HONUS*)PullREQ_GET_COUNTDOWN_HONUS;

@end
